# gabe/service.yml

apiVersion: v1
kind: Service
metadata:
  name: gabe-service
  labels:
    app: gabe
spec:
  type: LoadBalancer
  selector:
    app: gabe
  ports:
    - name: http
      port: 80
      targetPort: http